
from django.core.management.base import BaseCommand
from apps.menus.models import Menu

# 原始数据
RAW_MENUS_DATA = [
    {
        "id": 1,
        "parentId": 0,
        "name": "系统管理",
        "type": "CATALOG",
        "routeName": "",
        "routePath": "/system",
        "component": "Layout",
        "sort": 1,
        "visible": 1,
        "icon": "system",
        "redirect": "/system/user",
        "perm": None,
        "children": [
            {
                "id": 2,
                "parentId": 1,
                "name": "用户管理",
                "type": "MENU",
                "routeName": "User",
                "routePath": "user",
                "component": "system/user/index",
                "sort": 1,
                "visible": 1,
                "icon": "el-icon-User",
                "redirect": None,
                "perm": None,
                "children": [
                    {
                        "id": 105,
                        "parentId": 2,
                        "name": "用户查询",
                        "type": "BUTTON",
                        "routeName": None,
                        "routePath": "",
                        "component": None,
                        "sort": 0,
                        "visible": 1,
                        "icon": "",
                        "redirect": None,
                        "perm": "sys:user:query",
                        "children": [],
                    },
                    {
                        "id": 31,
                        "parentId": 2,
                        "name": "用户新增",
                        "type": "BUTTON",
                        "routeName": None,
                        "routePath": "",
                        "component": None,
                        "sort": 1,
                        "visible": 1,
                        "icon": "",
                        "redirect": "",
                        "perm": "sys:user:add",
                        "children": [],
                    },
                    {
                        "id": 32,
                        "parentId": 2,
                        "name": "用户编辑",
                        "type": "BUTTON",
                        "routeName": None,
                        "routePath": "",
                        "component": None,
                        "sort": 2,
                        "visible": 1,
                        "icon": "",
                        "redirect": "",
                        "perm": "sys:user:edit",
                        "children": [],
                    },
                    {
                        "id": 33,
                        "parentId": 2,
                        "name": "用户删除",
                        "type": "BUTTON",
                        "routeName": None,
                        "routePath": "",
                        "component": None,
                        "sort": 3,
                        "visible": 1,
                        "icon": "",
                        "redirect": "",
                        "perm": "sys:user:delete",
                        "children": [],
                    },
                    {
                        "id": 88,
                        "parentId": 2,
                        "name": "重置密码",
                        "type": "BUTTON",
                        "routeName": None,
                        "routePath": "",
                        "component": None,
                        "sort": 4,
                        "visible": 1,
                        "icon": "",
                        "redirect": None,
                        "perm": "sys:user:password:reset",
                        "children": [],
                    },
                    {
                        "id": 106,
                        "parentId": 2,
                        "name": "用户导入",
                        "type": "BUTTON",
                        "routeName": None,
                        "routePath": "",
                        "component": None,
                        "sort": 5,
                        "visible": 1,
                        "icon": "",
                        "redirect": None,
                        "perm": "sys:user:import",
                        "children": [],
                    },
                    {
                        "id": 107,
                        "parentId": 2,
                        "name": "用户导出",
                        "type": "BUTTON",
                        "routeName": None,
                        "routePath": "",
                        "component": None,
                        "sort": 6,
                        "visible": 1,
                        "icon": "",
                        "redirect": None,
                        "perm": "sys:user:export",
                        "children": [],
                    },
                ],
            },
            {
                "id": 3,
                "parentId": 1,
                "name": "角色管理",
                "type": "MENU",
                "routeName": "Role",
                "routePath": "role",
                "component": "system/role/index",
                "sort": 2,
                "visible": 1,
                "icon": "role",
                "redirect": None,
                "perm": None,
                "children": [
                    {
                        "id": 70,
                        "parentId": 3,
                        "name": "角色新增",
                        "type": "BUTTON",
                        "routeName": None,
                        "routePath": "",
                        "component": None,
                        "sort": 1,
                        "visible": 1,
                        "icon": "",
                        "redirect": None,
                        "perm": "sys:role:add",
                        "children": [],
                    },
                    {
                        "id": 71,
                        "parentId": 3,
                        "name": "角色编辑",
                        "type": "BUTTON",
                        "routeName": None,
                        "routePath": "",
                        "component": None,
                        "sort": 2,
                        "visible": 1,
                        "icon": "",
                        "redirect": None,
                        "perm": "sys:role:edit",
                        "children": [],
                    },
                    {
                        "id": 72,
                        "parentId": 3,
                        "name": "角色删除",
                        "type": "BUTTON",
                        "routeName": None,
                        "routePath": "",
                        "component": None,
                        "sort": 3,
                        "visible": 1,
                        "icon": "",
                        "redirect": None,
                        "perm": "sys:role:delete",
                        "children": [],
                    },
                ],
            },
            {
                "id": 4,
                "parentId": 1,
                "name": "菜单管理",
                "type": "MENU",
                "routeName": "Menu",
                "routePath": "menu",
                "component": "system/menu/index",
                "sort": 3,
                "visible": 1,
                "icon": "menu",
                "redirect": None,
                "perm": None,
                "children": [
                    {
                        "id": 73,
                        "parentId": 4,
                        "name": "菜单新增",
                        "type": "BUTTON",
                        "routeName": None,
                        "routePath": "",
                        "component": None,
                        "sort": 1,
                        "visible": 1,
                        "icon": "",
                        "redirect": None,
                        "perm": "sys:menu:add",
                        "children": [],
                    },
                    {
                        "id": 74,
                        "parentId": 4,
                        "name": "菜单编辑",
                        "type": "BUTTON",
                        "routeName": None,
                        "routePath": "",
                        "component": None,
                        "sort": 3,
                        "visible": 1,
                        "icon": "",
                        "redirect": None,
                        "perm": "sys:menu:edit",
                        "children": [],
                    },
                    {
                        "id": 75,
                        "parentId": 4,
                        "name": "菜单删除",
                        "type": "BUTTON",
                        "routeName": None,
                        "routePath": "",
                        "component": None,
                        "sort": 3,
                        "visible": 1,
                        "icon": "",
                        "redirect": None,
                        "perm": "sys:menu:delete",
                        "children": [],
                    },
                ],
            },
            {
                "id": 5,
                "parentId": 1,
                "name": "部门管理",
                "type": "MENU",
                "routeName": "Dept",
                "routePath": "dept",
                "component": "system/dept/index",
                "sort": 4,
                "visible": 1,
                "icon": "tree",
                "redirect": None,
                "perm": None,
                "children": [
                    {
                        "id": 76,
                        "parentId": 5,
                        "name": "部门新增",
                        "type": "BUTTON",
                        "routeName": None,
                        "routePath": "",
                        "component": None,
                        "sort": 1,
                        "visible": 1,
                        "icon": "",
                        "redirect": None,
                        "perm": "sys:dept:add",
                        "children": [],
                    },
                    {
                        "id": 77,
                        "parentId": 5,
                        "name": "部门编辑",
                        "type": "BUTTON",
                        "routeName": None,
                        "routePath": "",
                        "component": None,
                        "sort": 2,
                        "visible": 1,
                        "icon": "",
                        "redirect": None,
                        "perm": "sys:dept:edit",
                        "children": [],
                    },
                    {
                        "id": 78,
                        "parentId": 5,
                        "name": "部门删除",
                        "type": "BUTTON",
                        "routeName": None,
                        "routePath": "",
                        "component": None,
                        "sort": 3,
                        "visible": 1,
                        "icon": "",
                        "redirect": None,
                        "perm": "sys:dept:delete",
                        "children": [],
                    },
                ],
            },
            {
                "id": 6,
                "parentId": 1,
                "name": "字典管理",
                "type": "MENU",
                "routeName": "Dict",
                "routePath": "dict",
                "component": "system/dict/index",
                "sort": 5,
                "visible": 1,
                "icon": "dict",
                "redirect": None,
                "perm": None,
                "children": [
                    {
                        "id": 79,
                        "parentId": 6,
                        "name": "字典新增",
                        "type": "BUTTON",
                        "routeName": None,
                        "routePath": "",
                        "component": None,
                        "sort": 1,
                        "visible": 1,
                        "icon": "",
                        "redirect": None,
                        "perm": "sys:dict:add",
                        "children": [],
                    },
                    {
                        "id": 81,
                        "parentId": 6,
                        "name": "字典编辑",
                        "type": "BUTTON",
                        "routeName": None,
                        "routePath": "",
                        "component": None,
                        "sort": 2,
                        "visible": 1,
                        "icon": "",
                        "redirect": None,
                        "perm": "sys:dict_type:edit",
                        "children": [],
                    },
                    {
                        "id": 84,
                        "parentId": 6,
                        "name": "字典删除",
                        "type": "BUTTON",
                        "routeName": None,
                        "routePath": "",
                        "component": None,
                        "sort": 3,
                        "visible": 1,
                        "icon": "",
                        "redirect": None,
                        "perm": "sys:dict_type:delete",
                        "children": [],
                    },
                ],
            },
            {
                "id": 135,
                "parentId": 1,
                "name": "字典项",
                "type": "MENU",
                "routeName": "DictData",
                "routePath": "dict-item",
                "component": "system/dict/dict-item",
                "sort": 6,
                "visible": 0,
                "icon": "",
                "redirect": None,
                "perm": None,
                "children": [
                    {
                        "id": 136,
                        "parentId": 135,
                        "name": "字典项新增",
                        "type": "BUTTON",
                        "routeName": None,
                        "routePath": "",
                        "component": None,
                        "sort": 4,
                        "visible": 1,
                        "icon": "",
                        "redirect": None,
                        "perm": "sys:dict-item:add",
                        "children": [],
                    },
                    {
                        "id": 137,
                        "parentId": 135,
                        "name": "字典项编辑",
                        "type": "BUTTON",
                        "routeName": None,
                        "routePath": "",
                        "component": None,
                        "sort": 5,
                        "visible": 1,
                        "icon": "",
                        "redirect": None,
                        "perm": "sys:dict-item:edit",
                        "children": [],
                    },
                    {
                        "id": 138,
                        "parentId": 135,
                        "name": "字典项删除",
                        "type": "BUTTON",
                        "routeName": None,
                        "routePath": "",
                        "component": None,
                        "sort": 6,
                        "visible": 1,
                        "icon": "",
                        "redirect": None,
                        "perm": "sys:dict-item:delete",
                        "children": [],
                    },
                ],
            },
            {
                "id": 117,
                "parentId": 1,
                "name": "系统日志",
                "type": "MENU",
                "routeName": "Log",
                "routePath": "log",
                "component": "system/log/index",
                "sort": 6,
                "visible": 1,
                "icon": "document",
                "redirect": None,
                "perm": None,
                "children": [],
            },
            {
                "id": 120,
                "parentId": 1,
                "name": "系统配置",
                "type": "MENU",
                "routeName": "Config",
                "routePath": "config",
                "component": "system/config/index",
                "sort": 7,
                "visible": 1,
                "icon": "setting",
                "redirect": None,
                "perm": None,
                "children": [
                    {
                        "id": 121,
                        "parentId": 120,
                        "name": "查询系统配置",
                        "type": "BUTTON",
                        "routeName": None,
                        "routePath": "",
                        "component": None,
                        "sort": 1,
                        "visible": 1,
                        "icon": "",
                        "redirect": None,
                        "perm": "sys:config:query",
                        "children": [],
                    },
                    {
                        "id": 122,
                        "parentId": 120,
                        "name": "新增系统配置",
                        "type": "BUTTON",
                        "routeName": None,
                        "routePath": "",
                        "component": None,
                        "sort": 2,
                        "visible": 1,
                        "icon": "",
                        "redirect": None,
                        "perm": "sys:config:add",
                        "children": [],
                    },
                    {
                        "id": 123,
                        "parentId": 120,
                        "name": "修改系统配置",
                        "type": "BUTTON",
                        "routeName": None,
                        "routePath": "",
                        "component": None,
                        "sort": 3,
                        "visible": 1,
                        "icon": "",
                        "redirect": None,
                        "perm": "sys:config:update",
                        "children": [],
                    },
                    {
                        "id": 124,
                        "parentId": 120,
                        "name": "删除系统配置",
                        "type": "BUTTON",
                        "routeName": None,
                        "routePath": "",
                        "component": None,
                        "sort": 4,
                        "visible": 1,
                        "icon": "",
                        "redirect": None,
                        "perm": "sys:config:delete",
                        "children": [],
                    },
                    {
                        "id": 125,
                        "parentId": 120,
                        "name": "刷新系统配置",
                        "type": "BUTTON",
                        "routeName": None,
                        "routePath": "",
                        "component": None,
                        "sort": 5,
                        "visible": 1,
                        "icon": "",
                        "redirect": None,
                        "perm": "sys:config:refresh",
                        "children": [],
                    },
                ],
            },
            {
                "id": 126,
                "parentId": 1,
                "name": "通知公告",
                "type": "MENU",
                "routeName": "Notice",
                "routePath": "notice",
                "component": "system/notice/index",
                "sort": 9,
                "visible": 1,
                "icon": "",
                "redirect": None,
                "perm": None,
                "children": [
                    {
                        "id": 127,
                        "parentId": 126,
                        "name": "查询",
                        "type": "BUTTON",
                        "routeName": None,
                        "routePath": "",
                        "component": None,
                        "sort": 1,
                        "visible": 1,
                        "icon": "",
                        "redirect": None,
                        "perm": "sys:notice:query",
                        "children": [],
                    },
                    {
                        "id": 128,
                        "parentId": 126,
                        "name": "新增",
                        "type": "BUTTON",
                        "routeName": None,
                        "routePath": "",
                        "component": None,
                        "sort": 2,
                        "visible": 1,
                        "icon": "",
                        "redirect": None,
                        "perm": "sys:notice:add",
                        "children": [],
                    },
                    {
                        "id": 129,
                        "parentId": 126,
                        "name": "编辑",
                        "type": "BUTTON",
                        "routeName": None,
                        "routePath": "",
                        "component": None,
                        "sort": 3,
                        "visible": 1,
                        "icon": "",
                        "redirect": None,
                        "perm": "sys:notice:edit",
                        "children": [],
                    },
                    {
                        "id": 130,
                        "parentId": 126,
                        "name": "删除",
                        "type": "BUTTON",
                        "routeName": None,
                        "routePath": "",
                        "component": None,
                        "sort": 4,
                        "visible": 1,
                        "icon": "",
                        "redirect": None,
                        "perm": "sys:notice:delete",
                        "children": [],
                    },
                    {
                        "id": 133,
                        "parentId": 126,
                        "name": "发布",
                        "type": "BUTTON",
                        "routeName": None,
                        "routePath": "",
                        "component": None,
                        "sort": 5,
                        "visible": 1,
                        "icon": "",
                        "redirect": None,
                        "perm": "sys:notice:publish",
                        "children": [],
                    },
                    {
                        "id": 134,
                        "parentId": 126,
                        "name": "撤回",
                        "type": "BUTTON",
                        "routeName": None,
                        "routePath": "",
                        "component": None,
                        "sort": 6,
                        "visible": 1,
                        "icon": "",
                        "redirect": None,
                        "perm": "sys:notice:revoke",
                        "children": [],
                    },
                ],
            },
        ],
    },
    {
        "id": 118,
        "parentId": 0,
        "name": "系统工具",
        "type": "CATALOG",
        "routeName": None,
        "routePath": "/codegen",
        "component": "Layout",
        "sort": 2,
        "visible": 1,
        "icon": "menu",
        "redirect": None,
        "perm": None,
        "children": [
            {
                "id": 119,
                "parentId": 118,
                "name": "代码生成",
                "type": "MENU",
                "routeName": "Codegen",
                "routePath": "codegen",
                "component": "codegen/index",
                "sort": 1,
                "visible": 1,
                "icon": "code",
                "redirect": None,
                "perm": None,
                "children": [],
            },
        ],
    },
    {
        "id": 40,
        "parentId": 0,
        "name": "接口文档",
        "type": "CATALOG",
        "routeName": None,
        "routePath": "/api",
        "component": "Layout",
        "sort": 7,
        "visible": 1,
        "icon": "api",
        "redirect": "",
        "perm": None,
        "children": [
            {
                "id": 41,
                "parentId": 40,
                "name": "Apifox",
                "type": "MENU",
                "routeName": None,
                "routePath": "apifox",
                "component": "demo/api/apifox",
                "sort": 1,
                "visible": 1,
                "icon": "api",
                "redirect": "",
                "perm": None,
                "children": [],
            },
        ],
    },
    {
        "id": 26,
        "parentId": 0,
        "name": "平台文档",
        "type": "CATALOG",
        "routeName": None,
        "routePath": "/doc",
        "component": "Layout",
        "sort": 8,
        "visible": 1,
        "icon": "document",
        "redirect": "https://juejin.cn/post/7228990409909108793",
        "perm": None,
        "children": [
            {
                "id": 102,
                "parentId": 26,
                "name": "平台文档(内嵌)",
                "type": "EXTLINK",
                "routeName": None,
                "routePath": "internal-doc",
                "component": "demo/internal-doc",
                "sort": 1,
                "visible": 1,
                "icon": "document",
                "redirect": "",
                "perm": None,
                "children": [],
            },
            {
                "id": 30,
                "parentId": 26,
                "name": "平台文档(外链)",
                "type": "EXTLINK",
                "routeName": None,
                "routePath": "https://juejin.cn/post/7228990409909108793",
                "component": "",
                "sort": 2,
                "visible": 1,
                "icon": "link",
                "redirect": "",
                "perm": None,
                "children": [],
            },
        ],
    },
    {
        "id": 20,
        "parentId": 0,
        "name": "多级菜单",
        "type": "CATALOG",
        "routeName": None,
        "routePath": "/multi-level",
        "component": "Layout",
        "sort": 9,
        "visible": 1,
        "icon": "cascader",
        "redirect": "",
        "perm": None,
        "children": [
            {
                "id": 21,
                "parentId": 20,
                "name": "菜单一级",
                "type": "CATALOG",
                "routeName": None,
                "routePath": "multi-level1",
                "component": "Layout",
                "sort": 1,
                "visible": 1,
                "icon": "",
                "redirect": "",
                "perm": None,
                "children": [
                    {
                        "id": 22,
                        "parentId": 21,
                        "name": "菜单二级",
                        "type": "CATALOG",
                        "routeName": None,
                        "routePath": "multi-level2",
                        "component": "Layout",
                        "sort": 1,
                        "visible": 1,
                        "icon": "",
                        "redirect": None,
                        "perm": None,
                        "children": [
                            {
                                "id": 23,
                                "parentId": 22,
                                "name": "菜单三级-1",
                                "type": "MENU",
                                "routeName": None,
                                "routePath": "multi-level3-1",
                                "component": "demo/multi-level/children/children/level3-1",
                                "sort": 1,
                                "visible": 1,
                                "icon": "",
                                "redirect": "",
                                "perm": None,
                                "children": [],
                            },
                            {
                                "id": 24,
                                "parentId": 22,
                                "name": "菜单三级-2",
                                "type": "MENU",
                                "routeName": None,
                                "routePath": "multi-level3-2",
                                "component": "demo/multi-level/children/children/level3-2",
                                "sort": 2,
                                "visible": 1,
                                "icon": "",
                                "redirect": "",
                                "perm": None,
                                "children": [],
                            },
                        ],
                    },
                ],
            },
        ],
    },
    {
        "id": 36,
        "parentId": 0,
        "name": "组件封装",
        "type": "CATALOG",
        "routeName": None,
        "routePath": "/component",
        "component": "Layout",
        "sort": 10,
        "visible": 1,
        "icon": "menu",
        "redirect": "",
        "perm": None,
        "children": [
            {
                "id": 108,
                "parentId": 36,
                "name": "增删改查",
                "type": "MENU",
                "routeName": None,
                "routePath": "curd",
                "component": "demo/curd/index",
                "sort": 0,
                "visible": 1,
                "icon": "",
                "redirect": "",
                "perm": None,
                "children": [],
            },
            {
                "id": 109,
                "parentId": 36,
                "name": "列表选择器",
                "type": "MENU",
                "routeName": None,
                "routePath": "table-select",
                "component": "demo/table-select/index",
                "sort": 1,
                "visible": 1,
                "icon": "",
                "redirect": "",
                "perm": None,
                "children": [],
            },
            {
                "id": 37,
                "parentId": 36,
                "name": "富文本编辑器",
                "type": "MENU",
                "routeName": None,
                "routePath": "wang-editor",
                "component": "demo/wang-editor",
                "sort": 2,
                "visible": 1,
                "icon": "",
                "redirect": "",
                "perm": None,
                "children": [],
            },
            {
                "id": 38,
                "parentId": 36,
                "name": "图片上传",
                "type": "MENU",
                "routeName": None,
                "routePath": "upload",
                "component": "demo/upload",
                "sort": 3,
                "visible": 1,
                "icon": "",
                "redirect": "",
                "perm": None,
                "children": [],
            },
            {
                "id": 95,
                "parentId": 36,
                "name": "字典组件",
                "type": "MENU",
                "routeName": None,
                "routePath": "dict-demo",
                "component": "demo/dict",
                "sort": 4,
                "visible": 1,
                "icon": "",
                "redirect": "",
                "perm": None,
                "children": [],
            },
            {
                "id": 39,
                "parentId": 36,
                "name": "图标选择器",
                "type": "MENU",
                "routeName": None,
                "routePath": "icon-selector",
                "component": "demo/icon-selector",
                "sort": 4,
                "visible": 1,
                "icon": "",
                "redirect": "",
                "perm": None,
                "children": [],
            },
        ],
    },
    {
        "id": 110,
        "parentId": 0,
        "name": "路由参数",
        "type": "CATALOG",
        "routeName": None,
        "routePath": "/route-param",
        "component": "Layout",
        "sort": 11,
        "visible": 1,
        "icon": "el-icon-ElementPlus",
        "redirect": None,
        "perm": None,
        "children": [
            {
                "id": 111,
                "parentId": 110,
                "name": "参数(type=1)",
                "type": "MENU",
                "routeName": None,
                "routePath": "route-param-type1",
                "component": "demo/route-param",
                "sort": 1,
                "visible": 1,
                "icon": "el-icon-Star",
                "redirect": None,
                "perm": None,
                "children": [],
            },
            {
                "id": 112,
                "parentId": 110,
                "name": "参数(type=2)",
                "type": "MENU",
                "routeName": None,
                "routePath": "route-param-type2",
                "component": "demo/route-param",
                "sort": 2,
                "visible": 1,
                "icon": "el-icon-StarFilled",
                "redirect": None,
                "perm": None,
                "children": [],
            },
        ],
    },
    {
        "id": 89,
        "parentId": 0,
        "name": "功能演示",
        "type": "CATALOG",
        "routeName": None,
        "routePath": "/function",
        "component": "Layout",
        "sort": 12,
        "visible": 1,
        "icon": "menu",
        "redirect": "",
        "perm": None,
        "children": [
            {
                "id": 97,
                "parentId": 89,
                "name": "Icons",
                "type": "MENU",
                "routeName": None,
                "routePath": "icon-demo",
                "component": "demo/icons",
                "sort": 2,
                "visible": 1,
                "icon": "el-icon-Notification",
                "redirect": "",
                "perm": None,
                "children": [],
            },
            {
                "id": 90,
                "parentId": 89,
                "name": "Websocket",
                "type": "MENU",
                "routeName": None,
                "routePath": "/function/websocket",
                "component": "demo/websocket",
                "sort": 3,
                "visible": 1,
                "icon": "",
                "redirect": "",
                "perm": None,
                "children": [],
            },
            {
                "id": 91,
                "parentId": 89,
                "name": "敬请期待...",
                "type": "CATALOG",
                "routeName": None,
                "routePath": "other/:id",
                "component": "demo/other",
                "sort": 4,
                "visible": 1,
                "icon": "",
                "redirect": "",
                "perm": None,
                "children": [],
            },
        ],
    },
]


def create_menu_items(items, parent=None):
    for item in items:
        menu = Menu.objects.update_or_create(
            id=item['id'],
            defaults={
                'parent': parent,
                'name': item['name'],
                'type': item['type'],
                'route_name': item['routeName'] or '',
                'route_path': item['routePath'] or '',
                'component': item['component'] or '',
                'sort': item['sort'],
                'visible': bool(item['visible']),
                'icon': item['icon'] or '',
                'redirect': item['redirect'] or '',
                'perm': item['perm'],
            }
        )[0]
        if item.get('children'):
            create_menu_items(item['children'], parent=menu)


class Command(BaseCommand):
    help = '从 JSON 数据导入菜单'

    def handle(self, *args, **options):
        Menu.objects.all().delete()  # 清空旧数据
        create_menu_items(RAW_MENUS_DATA)
        self.stdout.write(self.style.SUCCESS('✅ 菜单数据导入成功！'))

